replicaCount: 1

image:
  repository: raulnq/helm-sandbox-app
  pullPolicy: IfNotPresent
  tag: "1.0"
  
tests:
  repository: raulnq/helm-sandbox-tests
  pullPolicy: IfNotPresent
  tag: "1.0"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80